# Generated by Django 3.2 on 2021-04-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_taskitems_taskitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='id',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='task_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
