# Generated by Django 3.2 on 2021-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210422_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
